<group>
 key=$hh_top_l
 group=200$hh_top_l000 off_by=100000000
 locc$FC=0 hicc$FC=7
#include "hihats/hh13_stx_top_l_a.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l001 off_by=100001000
 locc$FC=8 hicc$FC=15
#include "hihats/hh13_stx_top_l_b.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l002 off_by=100002000
 locc$FC=16 hicc$FC=23
#include "hihats/hh13_stx_top_l_c.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l003 off_by=100003000
 locc$FC=24 hicc$FC=31
#include "hihats/hh13_stx_top_l_d.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l004 off_by=100004000
 locc$FC=32 hicc$FC=39
#include "hihats/hh13_stx_top_l_e.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l005 off_by=100005000
 locc$FC=40 hicc$FC=47
#include "hihats/hh13_stx_top_l_f.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l006 off_by=100006000
 locc$FC=48 hicc$FC=55
#include "hihats/hh13_stx_top_l_g.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l007 off_by=100007000
 locc$FC=56 hicc$FC=63
#include "hihats/hh13_stx_top_l_h.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l008 off_by=100008000
 locc$FC=64 hicc$FC=71
#include "hihats/hh13_stx_top_l_i.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l009 off_by=100009000
 locc$FC=72 hicc$FC=79
#include "hihats/hh13_stx_top_l_j.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l010 off_by=100010000
 locc$FC=80 hicc$FC=87
#include "hihats/hh13_stx_top_l_k.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l011 off_by=100011000
 locc$FC=88 hicc$FC=95
#include "hihats/hh13_stx_top_l_l.sfz"
<group>
 key=$hh_top_l
 group=200$hh_top_l012 off_by=100012000
 locc$FC=96 hicc$FC=127
#include "hihats/hh13_stx_top_l_m.sfz"
