<group>
 key=$hh_ord_l
 group=200$hh_ord_l000 off_by=100000000
 locc$FC=0 hicc$FC=7
#include "hihats/hh13_mlt_ord_l_a.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l001 off_by=100001000
 locc$FC=8 hicc$FC=15
#include "hihats/hh13_mlt_ord_l_b.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l002 off_by=100002000
 locc$FC=16 hicc$FC=23
#include "hihats/hh13_mlt_ord_l_c.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l003 off_by=100003000
 locc$FC=24 hicc$FC=31
#include "hihats/hh13_mlt_ord_l_d.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l004 off_by=100004000
 locc$FC=32 hicc$FC=39
#include "hihats/hh13_mlt_ord_l_e.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l005 off_by=100005000
 locc$FC=40 hicc$FC=127
#include "hihats/hh13_mlt_ord_l_f.sfz"
