<group>
 key=$hh_ord_l
 group=200$hh_ord_l000 off_by=100000000
 locc$FC=120 hicc$FC=127
#include "hihats/hh13_brs_ord_l_a.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l001 off_by=100001000
 locc$FC=112 hicc$FC=119
#include "hihats/hh13_brs_ord_l_b.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l002 off_by=100002000
 locc$FC=104 hicc$FC=111
#include "hihats/hh13_brs_ord_l_c.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l003 off_by=100003000
 locc$FC=96 hicc$FC=103
#include "hihats/hh13_brs_ord_l_d.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l004 off_by=100004000
 locc$FC=88 hicc$FC=95
#include "hihats/hh13_brs_ord_l_e.sfz"
<group>
 key=$hh_ord_l
 group=200$hh_ord_l005 off_by=100005000
 locc$FC=0 hicc$FC=87
#include "hihats/hh13_brs_ord_l_f.sfz"
