<group>
 key=$hh_ped
 group=200$hh_ped007 off_by=100007000
 locc$FC=0 hicc$FC=63
#include "hihats/hh13_ped_h.sfz"
<group>
 key=$hh_ped
 group=200$hh_ped009 off_by=100009000
 locc$FC=64 hicc$FC=79
#include "hihats/hh13_ped_j.sfz"
<group>
 key=$hh_ped
 group=200$hh_ped012 off_by=100012000
 locc$FC=80 hicc$FC=103
#include "hihats/hh13_ped_m.sfz"
<group>
 key=$hh_ped
 group=200$hh_ped015 off_by=100015000
 locc$FC=104 hicc$FC=127
#include "hihats/hh13_ped_p.sfz"
