<group>
 key=$hh_grb
 group=200$hh_grb004 off_by=100004000
 locc$FC=0 hicc$FC=39
#include "hihats/hh13_stx_grb_e.sfz"
<group>
 key=$hh_grb
 group=200$hh_grb007 off_by=100007000
 locc$FC=40 hicc$FC=63
#include "hihats/hh13_stx_grb_h.sfz"
<group>
 key=$hh_grb
 group=200$hh_grb009 off_by=100009000
 locc$FC=64 hicc$FC=79
#include "hihats/hh13_stx_grb_j.sfz"
<group>
 key=$hh_grb
 group=200$hh_grb012 off_by=100012000
 locc$FC=80 hicc$FC=103
#include "hihats/hh13_stx_grb_m.sfz"
<group>
 key=$hh_grb
 group=200$hh_grb015 off_by=100015000
 locc$FC=104 hicc$FC=127
#include "hihats/hh13_stx_grb_p.sfz"
