<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel000 off_by=100000000
 locc$FC=0 hicc$FC=7
#include "hihats/hh13_stx_bel_a.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel003 off_by=100003000
 locc$FC=8 hicc$FC=31
#include "hihats/hh13_stx_bel_d.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel006 off_by=100006000
 locc$FC=32 hicc$FC=55
#include "hihats/hh13_stx_bel_g.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel009 off_by=100009000
 locc$FC=56 hicc$FC=79
#include "hihats/hh13_stx_bel_j.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel012 off_by=100012000
 locc$FC=80 hicc$FC=103
#include "hihats/hh13_stx_bel_m.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel015 off_by=100015000
 locc$FC=104 hicc$FC=127
#include "hihats/hh13_stx_bel_p.sfz"
