<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel000 off_by=100000000
 locc$FC=120 hicc$FC=127
#include "hihats/hh13_stx_bel_a.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel003 off_by=100003000
 locc$FC=96 hicc$FC=119
#include "hihats/hh13_stx_bel_d.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel006 off_by=100006000
 locc$FC=72 hicc$FC=95
#include "hihats/hh13_stx_bel_g.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel009 off_by=100009000
 locc$FC=48 hicc$FC=71
#include "hihats/hh13_stx_bel_j.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel012 off_by=100012000
 locc$FC=24 hicc$FC=47
#include "hihats/hh13_stx_bel_m.sfz"
<group>
 key=$hh_bel
 locc$MOD=000 hicc$MOD=126
 group=200$hh_bel015 off_by=100015000
 locc$FC=0 hicc$FC=23
#include "hihats/hh13_stx_bel_p.sfz"
