<group>
 key=$hh_top_r
 group=200$hh_top_r000 off_by=100000000
 locc$FC=120 hicc$FC=127
#include "hihats/hh13_stx_top_r_a.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r001 off_by=100001000
 locc$FC=112 hicc$FC=119
#include "hihats/hh13_stx_top_r_b.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r002 off_by=100002000
 locc$FC=104 hicc$FC=111
#include "hihats/hh13_stx_top_r_c.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r003 off_by=100003000
 locc$FC=96 hicc$FC=103
#include "hihats/hh13_stx_top_r_d.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r004 off_by=100004000
 locc$FC=88 hicc$FC=95
#include "hihats/hh13_stx_top_r_e.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r005 off_by=100005000
 locc$FC=80 hicc$FC=87
#include "hihats/hh13_stx_top_r_f.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r006 off_by=100006000
 locc$FC=72 hicc$FC=79
#include "hihats/hh13_stx_top_r_g.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r007 off_by=100007000
 locc$FC=64 hicc$FC=71
#include "hihats/hh13_stx_top_r_h.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r008 off_by=100008000
 locc$FC=56 hicc$FC=63
#include "hihats/hh13_stx_top_r_i.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r009 off_by=100009000
 locc$FC=48 hicc$FC=55
#include "hihats/hh13_stx_top_r_j.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r010 off_by=100010000
 locc$FC=40 hicc$FC=47
#include "hihats/hh13_stx_top_r_k.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r011 off_by=100011000
 locc$FC=32 hicc$FC=39
#include "hihats/hh13_stx_top_r_l.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r012 off_by=100012000
 locc$FC=24 hicc$FC=31
#include "hihats/hh13_stx_top_r_m.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r013 off_by=100013000
 locc$FC=16 hicc$FC=23
#include "hihats/hh13_stx_top_r_n.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r014 off_by=100014000
 locc$FC=8 hicc$FC=15
#include "hihats/hh13_stx_top_r_o.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r015 off_by=100015000
 locc$FC=0 hicc$FC=7
#include "hihats/hh13_stx_top_r_p.sfz"
