<group>
 key=$hh_ord_r
 group=200$hh_ord_r000 off_by=100000000
 locc$FC=0 hicc$FC=7
#include "hihats/hh14_stx_ord_r_a.sfz"
<group>
 key=$hh_ord_r
 group=200$hh_ord_r001 off_by=100001000
 locc$FC=8 hicc$FC=15
#include "hihats/hh14_stx_ord_r_b.sfz"
<group>
 key=$hh_ord_r
 group=200$hh_ord_r002 off_by=100002000
 locc$FC=16 hicc$FC=23
#include "hihats/hh14_stx_ord_r_c.sfz"
<group>
 key=$hh_ord_r
 group=200$hh_ord_r003 off_by=100003000
 locc$FC=24 hicc$FC=31
#include "hihats/hh14_stx_ord_r_d.sfz"
<group>
 key=$hh_ord_r
 group=200$hh_ord_r004 off_by=100004000
 locc$FC=32 hicc$FC=127
#include "hihats/hh14_stx_ord_r_e.sfz"
