<group>
 key=$hh_top_r
 group=200$hh_top_r000 off_by=100000000
 locc$FC=120 hicc$FC=127
#include "hihats/hh14_stx_top_r_a.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r001 off_by=100001000
 locc$FC=112 hicc$FC=119
#include "hihats/hh14_stx_top_r_b.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r002 off_by=100002000
 locc$FC=104 hicc$FC=111
#include "hihats/hh14_stx_top_r_c.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r003 off_by=100003000
 locc$FC=96 hicc$FC=103
#include "hihats/hh14_stx_top_r_d.sfz"
<group>
 key=$hh_top_r
 group=200$hh_top_r004 off_by=100004000
 locc$FC=0 hicc$FC=95
#include "hihats/hh14_stx_top_r_e.sfz"
