<group>
 key=$tm10_l
 locc$MOD=000 hicc$MOD=045
#include "toms/tm10_bop_stx_snare_off_ord_l.sfz"
<group>
 key=$tm10_r
 locc$MOD=000 hicc$MOD=045
#include "toms/tm10_bop_stx_snare_off_ord_r.sfz"
<group>
 key=$tm10_l
 locc$MOD=127 hicc$MOD=127
#include "toms/tm10_bop_stx_snare_off_rim.sfz"
<group>
 key=$tm10_r
 locc$MOD=086 hicc$MOD=127
#include "toms/tm10_bop_stx_snare_off_rim.sfz"
<group>
 key=$tm10_l
 locc$MOD=046 hicc$MOD=126
#include "toms/tm10_bop_stx_snare_off_rms_l.sfz"
<group>
 key=$tm10_r
 locc$MOD=046 hicc$MOD=085
#include "toms/tm10_bop_stx_snare_off_rms_r.sfz"
