<group>
 key=$tm14_l
 locc$MOD=127 hicc$MOD=127
#include "toms/tm14_rock_stx_snare_off_rim.sfz"
<group>
 key=$tm14_r
 locc$MOD=086 hicc$MOD=127
#include "toms/tm14_rock_stx_snare_off_rim.sfz"
<group>
 key=$tm14_l
 locc$MOD=000 hicc$MOD=126
#include "toms/tm14_rock_stx_snare_on_ord_l.sfz"
<group>
 key=$tm14_r
 locc$MOD=000 hicc$MOD=045
#include "toms/tm14_rock_stx_snare_on_ord_r.sfz"
<group>
 key=$tm14_r
 locc$MOD=046 hicc$MOD=085
#include "toms/tm14_rock_stx_snare_on_rms_r.sfz"
