#define $sn_xtka 13
#define $sn_ord_l 14
#define $sn_e2c_l 14
#define $sn_rms_l 15
#define $sn_rmh_l 15
#define $sn_rim_l 15
#define $sn_prs_l 16
#define $sn_rol_l 16
#define $sn_xtkb 37
#define $sn_ord_r 38
#define $sn_e2c_r 38
#define $sn_rms_r 39
#define $sn_rmh_r 39
#define $sn_rim_r 39
#define $sn_prs_r 40
#define $sn_rol_r 40

<group>
 key=$sn_ord_l
#include "snares/sn12_bop_muted_stx_snare_off_ord_l.sfz"
<group>
 key=$sn_ord_r
#include "snares/sn12_bop_muted_stx_snare_off_ord_r.sfz"
<group>
 key=$sn_rms_l
#include "snares/sn12_bop_muted_stx_snare_off_rms_l.sfz"
<group>
 key=$sn_rms_r
#include "snares/sn12_bop_muted_stx_snare_off_rms_r.sfz"
