<group>
 key=$cy_china_19_ord
 group=500$cy_china_19_ord000
 locc$MOD=127 hicc$MOD=127
#include "cymbals/china_cy19_stx_grb.sfz"
<group>
 key=$cy_china_19_ord
 group=600$cy_china_19_ord000 off_by=500$cy_china_19_ord000
 locc$MOD=000 hicc$MOD=126
#include "cymbals/china_cy19_stx_ord.sfz"
<group>
 key=$cy_china_19_top
 group=600$cy_china_19_ord000 off_by=500$cy_china_19_ord000
 locc$MOD=000 hicc$MOD=085
#include "cymbals/china_cy19_stx_top.sfz"
