<group>
 key=$cy_crash_18_ord
 group=500$cy_crash_18_ord000
 locc$MOD=127 hicc$MOD=127
#include "cymbals/crash_cy18_brs_grb.sfz"
<group>
 key=$cy_crash_18_ord
 group=600$cy_crash_18_ord000 off_by=500$cy_crash_18_ord000
 locc$MOD=000 hicc$MOD=126
#include "cymbals/crash_cy18_brs_ord.sfz"
<group>
 key=$cy_crash_18_top
 group=600$cy_crash_18_ord000 off_by=500$cy_crash_18_ord000
 locc$MOD=000 hicc$MOD=045
#include "cymbals/crash_cy18_brs_ord.sfz"
<group>
 key=$cy_crash_18_top
 group=600$cy_crash_18_ord000 off_by=500$cy_crash_18_ord000
 locc$MOD=046 hicc$MOD=127
#include "cymbals/crash_cy18_brs_sws.sfz"
