<group>
 key=$cy_ride_20_bel
 group=600$cy_ride_20_ord000 off_by=500$cy_ride_20_ord000
#include "cymbals/ride_cy20_stx_bel.sfz"
<group>
 key=$cy_ride_20_top
 group=600$cy_ride_20_ord000 off_by=500$cy_ride_20_ord000
 locc$MOD=000 hicc$MOD=085
#include "cymbals/ride_cy20_stx_elv.sfz"
<group>
 key=$cy_ride_20_ord
 group=500$cy_ride_20_ord000
 locc$MOD=127 hicc$MOD=127
#include "cymbals/ride_cy20_stx_grb.sfz"
<group>
 key=$cy_ride_20_ord
 group=600$cy_ride_20_ord000 off_by=500$cy_ride_20_ord000
 locc$MOD=000 hicc$MOD=126
#include "cymbals/ride_cy20_stx_ord.sfz"
<group>
 key=$cy_ride_20_top
 group=600$cy_ride_20_ord000 off_by=500$cy_ride_20_ord000
 locc$MOD=086 hicc$MOD=127
#include "cymbals/ride_cy20_stx_rim.sfz"
