<group>
 key=$cy_sizzle_19_bel
 group=600$cy_sizzle_19_ord000 off_by=500$cy_sizzle_19_ord000
#include "cymbals/sizzle_cy19_stx_bel.sfz"
<group>
 key=$cy_sizzle_19_top
 group=600$cy_sizzle_19_ord000 off_by=500$cy_sizzle_19_ord000
 locc$MOD=086 hicc$MOD=126
#include "cymbals/sizzle_cy19_stx_elv.sfz"
<group>
 key=$cy_sizzle_19_ord
 group=500$cy_sizzle_19_ord000
 locc$MOD=127 hicc$MOD=127
#include "cymbals/sizzle_cy19_stx_grb.sfz"
<group>
 key=$cy_sizzle_19_ord
 group=600$cy_sizzle_19_ord000 off_by=500$cy_sizzle_19_ord000
 locc$MOD=000 hicc$MOD=126
#include "cymbals/sizzle_cy19_stx_ord.sfz"
