<group>
 key=$cy_splash_12_ord
 group=500$cy_splash_12_ord000
 locc$MOD=127 hicc$MOD=127
#include "cymbals/splash_cy12_brs_grb.sfz"
<group>
 key=$cy_splash_12_ord
 group=600$cy_splash_12_ord000 off_by=500$cy_splash_12_ord000
 locc$MOD=000 hicc$MOD=126
#include "cymbals/splash_cy12_brs_ord.sfz"
<group>
 key=$cy_splash_12_top
 group=600$cy_splash_12_ord000 off_by=500$cy_splash_12_ord000
 locc$MOD=000 hicc$MOD=045
#include "cymbals/splash_cy12_brs_ord.sfz"
<group>
 key=$cy_splash_12_top
 group=600$cy_splash_12_ord000 off_by=500$cy_splash_12_ord000
 locc$MOD=046 hicc$MOD=127
#include "cymbals/splash_cy12_brs_sws.sfz"
